language: clojure
addons:
  apt:
    packages:
      - phantomjs
install:
  - curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod +x lein
script:
  - ./lein doo phantom cljs-test once
  - ./lein test